### ISSUE TITLE
STOP is now not working any more

### ISSUE THREAD

**Issue by Dante1975X** [OpenVoiceOS/ovos-ocp-audio-plugin#111]
Back in February the STOP command was stopping the playing of songs (youtube-music-skill) or radio music (tunein-skill). But it worked not properly (see issue #110). Since 2 or 3 weeks the STOP command is completely not working. There is no reaction on STOP. Other commands like "PAUSE" or "RESUME" are still working.

**Comment by JarbasAl** [comment]
maybe works with the new pipeline https://openvoiceos.github.io/ovos-technical-manual/OCP_pipeline/ + #112

**Comment by Dante1975X** [comment]
> maybe works with the new pipeline https://openvoiceos.github.io/ovos-technical-manual/OCP_pipeline/ + #112

I'm not sure, if I understand right. I have added this to my mycroft.conf, but there was no change. STOP is still not working.

```
   // Intent Pipeline / plugins config
  "intents" : {

    "pipeline": [
        "stop_high",
        "converse",
        "ocp_high",
        "padatious_high",
        "adapt_high",
        "fallback_high",
        "stop_medium",
        "adapt_medium",
        "padatious_medium",
        "adapt_low",
        "common_qa",
        "ocp_medium",
        "fallback_medium",
        "ocp_fallback",
        "fallback_low"
    ]
  },
```
In the audio logs I can see this error message, when I use "STOP".
```

2024-05-11 20:58:11.921 - audio - ovos_plugin_common_play.ocp.player:resume:568 - DEBUG - Resuming playback: 3

exception calling callback for <Future at 0x71f4dff70ed0 state=finished raised TypeError>

Traceback (most recent call last):

  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks

    callback(self)

  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback

    self.emit("error", exc)

  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit

    self._emit_handle_potential_error(event, args[0] if args else None)

  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error

    raise error

  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: AudioService._restore_volume_after_record.<locals>.restore_volume() takes 0 positional arguments but 1 was given

2024-05-11 20:58:11.942 - audio - ovos_plugin_vlc:track_start:67 - DEBUG - VLC playback start
```

**Comment by JarbasAl** [comment]
NLP moved to ovos-core directly, uncoupled from the OCP plugin

you are missing ` "experimental_ocp_pipeline": true,`  to enable it, we are testing to see if it should be made a default on release 0.0.8 or if it needs more time and should only be enabled in 0.1.0, so for now that flag needs to be set for those who want to experiment

**Comment by Dante1975X** [comment]
Okay. I tried with the following. Still no change. STOP is not working. Same error message.

The link with the test case I don't understand. That is too much "code" for me. Sorry, I'm only a "user".

```
  "intents" : {
    "experimental_ocp_pipeline": true,
    "pipeline": [
        "stop_high",
        "converse",
        "ocp_high",
        "padatious_high",
        "adapt_high",
        "fallback_high",
        "stop_medium",
        "adapt_medium",
        "padatious_medium",
        "adapt_low",
        "common_qa",
        "ocp_medium",
        "fallback_medium",
        "ocp_fallback",
        "fallback_low"
    ]
  },
```

**Comment by JarbasAl** [comment]
please share core logs to see what ovos is trying to do when it hears stop

and also try having ocp_high before stop_high

```
        "converse",
        "ocp_high",
        "stop_high",
```

**Comment by Dante1975X** [comment]
I tried now with this version. No change. In ovos-core there is no log-reaction at all, when I use STOP.  And I already use log-level DEBUG.

```
// Intent Pipeline / plugins config
  "intents" : {
    "experimental_ocp_pipeline": true,
    "pipeline": [
        "ocp_high",
        "stop_high",
        "converse",
        "padatious_high",
        "adapt_high",
        "fallback_high",
        "stop_medium",
        "adapt_medium",
        "padatious_medium",
        "adapt_low",
        "common_qa",
        "ocp_medium",
        "fallback_medium",
        "ocp_fallback",
        "fallback_low"
    ]
  },
```

**Comment by Dante1975X** [comment]
It's strange. When I give the STOP command via voice, then there is no reaction in core log. But when I give the command via ovos-cli-client, then there is the following log, but music is still playing.
```

2024-05-11 21:48:42.822 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-cancel: {}

2024-05-11 21:48:42.822 - skills - ovos_core.transformers:transform:63 - WARNING - ovos-utterance-corrections transform exception: list index out of range

2024-05-11 21:48:42.823 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-normalizer: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'de-de'}

2024-05-11 21:48:42.825 - skills - ovos_core.intent_services:get_pipeline:263 - DEBUG - Session pipeline: ['ocp_high', 'stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'ocp_medium', 'fallback_medium', 'ocp_fallback', 'fallback_low']

2024-05-11 21:48:42.826 - skills - padacioso:calc_intent:240 - INFO - No match

2024-05-11 21:48:42.827 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method OCPPipelineMatcher.match_high of <ovos_core.intent_services.ocp_service.OCPPipelineMatcher object at 0x75a90aea6e10>>

2024-05-11 21:48:42.827 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x75a90aeab590>>

2024-05-11 21:48:42.874 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x75a90ae467d0>>

2024-05-11 21:48:42.874 - skills - ovos_core.intent_services.padatious_service:_match_level:50 - DEBUG - Padatious Matching confidence > 0.95

2024-05-11 21:48:42.876 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - intent matching took: 0.05149340629577637

ovos.common_play stopped: None

skill-ovos-youtube-music.openvoiceos stopped: None

skill-ovos-boot-finished.openvoiceos stopped: None

skill-ovos-news.openvoiceos stopped: None

skill-openhab stopped: None
```

Here is the listener log. It seems there is nothing transcribed. But other commands like "What time is it" or "PAUSE" the listener transcribes correct???

```
2024-05-11 21:58:03.319 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_detect_ww:471 - DEBUG - Wake word detected=hey_mycroft

2024-05-11 21:58:03.320 - voice - ovos_dinkum_listener.service:_hotword_audio:618 - DEBUG - Handling listen sound: snd/start_listening.wav

2024-05-11 21:58:03.321 - voice - ovos_dinkum_listener.service:_hotword_audio:642 - DEBUG - Emitting hotword event: recognizer_loop:wakeword

2024-05-11 21:58:03.321 - voice - ovos_dinkum_listener.service:_record_begin:501 - DEBUG - Record begin

2024-05-11 21:58:03.324 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:225 - INFO - Wakeword detected

2024-05-11 21:58:03.830 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:252 - DEBUG - STATE: ListeningState.BEFORE_COMMAND

2024-05-11 21:58:03.914 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.086 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.171 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.342 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.426 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.598 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.683 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 21:58:04.684 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_before_cmd:585 - DEBUG - STATE: ListeningState.IN_COMMAND

2024-05-11 21:58:04.854 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:04.939 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:05.110 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:05.195 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:05.366 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:05.451 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 21:58:05.452 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_in_cmd:624 - DEBUG - STATE: ListeningState.AFTER_COMMAND

2024-05-11 21:58:05.622 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:261 - INFO - speech finished

2024-05-11 21:58:05.641 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:703 - DEBUG - removed silence from utterance

2024-05-11 21:58:05.642 - voice - ovos_stt_plugin_server:execute:40 - DEBUG - Using user defined urls ['http://192.168.2.222:8082/stt', 'http://192.168.1.227:8083/stt']

2024-05-11 21:58:05.643 - voice - ovos_stt_plugin_server:execute:47 - DEBUG - chosen url http://192.168.2.222:8082/stt

2024-05-11 21:58:05.911 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:712 - INFO - nothing transcribed

2024-05-11 21:58:05.912 - voice - ovos_dinkum_listener.service:_record_end_signal:651 - DEBUG - Record end

2024-05-11 21:58:05.913 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:733 - DEBUG - STATE: ListeningState.DETECT_WAKEWORD

2024-05-11 21:58:05.913 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:744 - DEBUG - reset VAD
```

**Comment by JarbasAl** [comment]
you seem to be running into https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/110

**Comment by JarbasAl** [comment]
from your core logs, seems like OCPPipeline is not detecting the player is active?  (So doesnt match stop)

does it match pause/resume?

**Comment by JarbasAl** [comment]
the first error log you shared is unrelated to stop, fixed https://github.com/OpenVoiceOS/ovos-audio/issues/65

**Comment by Dante1975X** [comment]
pause and resume are trancribed correct and there is a correct reaction.

Here is an log example with pause
```

2024-05-11 22:11:23.072 - voice - ovos_dinkum_listener.voice_loop.hotwords:found:259 - DEBUG - Detected wake_word: hey_mycroft

2024-05-11 22:11:23.073 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_detect_ww:471 - DEBUG - Wake word detected=hey_mycroft

2024-05-11 22:11:23.074 - voice - ovos_dinkum_listener.service:_hotword_audio:618 - DEBUG - Handling listen sound: snd/start_listening.wav

2024-05-11 22:11:23.075 - voice - ovos_dinkum_listener.service:_hotword_audio:642 - DEBUG - Emitting hotword event: recognizer_loop:wakeword

2024-05-11 22:11:23.075 - voice - ovos_dinkum_listener.service:_record_begin:501 - DEBUG - Record begin

2024-05-11 22:11:23.083 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:225 - INFO - Wakeword detected

2024-05-11 22:11:23.583 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:252 - DEBUG - STATE: ListeningState.BEFORE_COMMAND

2024-05-11 22:11:23.669 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:23.839 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:23.925 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:24.096 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:24.181 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:24.351 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:24.437 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:255 - DEBUG - waiting for speech

2024-05-11 22:11:24.439 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_before_cmd:585 - DEBUG - STATE: ListeningState.IN_COMMAND

2024-05-11 22:11:24.608 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:24.693 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:24.864 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:24.949 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:25.119 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:25.205 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:25.375 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:258 - DEBUG - recording speech

2024-05-11 22:11:25.377 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_in_cmd:624 - DEBUG - STATE: ListeningState.AFTER_COMMAND

2024-05-11 22:11:25.461 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:261 - INFO - speech finished

2024-05-11 22:11:25.487 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:703 - DEBUG - removed silence from utterance

2024-05-11 22:11:25.488 - voice - ovos_stt_plugin_server:execute:40 - DEBUG - Using user defined urls ['http://192.168.2.222:8082/stt', 'http://192.168.1.227:8083/stt']

2024-05-11 22:11:25.489 - voice - ovos_stt_plugin_server:execute:47 - DEBUG - chosen url http://192.168.2.222:8082/stt

2024-05-11 22:11:25.804 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:709 - DEBUG - transformers metadata: {'client_name': 'ovos_dinkum_listener', 'source': 'audio', 'destination': ['skills'], 'transcription': 'Pause'}

2024-05-11 22:11:25.805 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:710 - INFO - transcribed: Pause

2024-05-11 22:11:25.806 - voice - ovos_dinkum_listener.service:_record_end_signal:651 - DEBUG - Record end

2024-05-11 22:11:25.806 - voice - ovos_dinkum_listener.service:_stt_text:669 - DEBUG - STT: Pause

2024-05-11 22:11:25.807 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:733 - DEBUG - STATE: ListeningState.DETECT_WAKEWORD

2024-05-11 22:11:25.810 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:744 - DEBUG - reset VAD
```

```
2024-05-11 22:11:25.824 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-cancel: {}

2024-05-11 22:11:25.824 - skills - ovos_core.transformers:transform:63 - WARNING - ovos-utterance-corrections transform exception: list index out of range

2024-05-11 22:11:25.825 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-normalizer: {'client_name': 'ovos_dinkum_listener', 'source': 'audio', 'destination': ['skills'], 'transcription': 'Pause', 'lang': 'de-de'}

2024-05-11 22:11:25.827 - skills - ovos_core.intent_services:get_pipeline:263 - DEBUG - Session pipeline: ['ocp_high', 'stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'ocp_medium', 'fallback_medium', 'ocp_fallback', 'fallback_low']

2024-05-11 22:11:25.836 - skills - padacioso:calc_intent:240 - INFO - No match

2024-05-11 22:11:25.837 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method OCPPipelineMatcher.match_high of <ovos_core.intent_services.ocp_service.OCPPipelineMatcher object at 0x7c261358a210>>

2024-05-11 22:11:25.837 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x7c2613fa0250>>

2024-05-11 22:11:25.901 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x7c2613f3ead0>>

2024-05-11 22:11:25.902 - skills - ovos_core.intent_services.padatious_service:_match_level:50 - DEBUG - Padatious Matching confidence > 0.95

2024-05-11 22:11:25.907 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - intent matching took: 0.07561469078063965

```
2024-05-11 22:11:25.833 - audio - ovos_plugin_vlc:track_start:67 - DEBUG - VLC playback start

2024-05-11 22:11:25.834 - audio - ovos_audio.audio:track_start:163 - DEBUG - New track coming up!

2024-05-11 22:11:25.923 - audio - ovos_plugin_common_play.ocp.player:pause:547 - DEBUG - Pausing playback: 3
```
```

**Comment by JarbasAl** [comment]
` no match from <bound method OCPPipelineMatcher.match_high `  <- OCP is not matching for you

I also see your lang is `de-de` , so you need to translate a bunch of OCP files before it will work https://github.com/OpenVoiceOS/ovos-core/tree/dev/ovos_core/intent_services/locale/en-us

but it seems padatious is, which indicates you are using the old OCP intents.... are you missing this PR? https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/pull/112

for all intents and purposes you are running the old OCP and skipping the Pipeline

**Comment by Dante1975X** [comment]
You were right. Even I did an update of all my ovos docker containers this evening, I was still on version 0.0.7a2. I now updated manually via audio.list to 0.0.7a3.

I see now this in audio log:
```
2024-05-11 23:08:22.846 - audio - ovos_plugin_common_play.ocp:register_media_intents:124 - INFO - Using Classic OCP with experimental OCP pipeline

2024-05-11 23:08:22.847 - audio - ovos_plugin_common_play.ocp:register_media_intents:125 - DEBUG - skipping Classic OCP intent registering
```


But still no change in results. No reaction on stop via voice. Stop via ovos-cli-client results in the following log:

```
2024-05-11 23:17:15.216 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-cancel: {}

2024-05-11 23:17:15.216 - skills - ovos_core.transformers:transform:63 - WARNING - ovos-utterance-corrections transform exception: list index out of range

2024-05-11 23:17:15.218 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-normalizer: {'client_name': 'ovos_dinkum_listener', 'source': 'audio', 'destination': ['skills'], 'transcription': 'Spiele weiter', 'lang': 'de-de'}

2024-05-11 23:17:15.220 - skills - ovos_core.intent_services:get_pipeline:263 - DEBUG - Session pipeline: ['ocp_high', 'stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'ocp_medium', 'fallback_medium', 'ocp_fallback', 'fallback_low']

2024-05-11 23:17:15.221 - skills - padacioso:calc_intent:240 - INFO - No match

2024-05-11 23:17:15.222 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method OCPPipelineMatcher.match_high of <ovos_core.intent_services.ocp_service.OCPPipelineMatcher object at 0x75cbe0370190>>

2024-05-11 23:17:15.223 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x75cbe0597090>>

2024-05-11 23:17:15.237 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x75cbe0536910>>

2024-05-11 23:17:15.238 - skills - ovos_core.intent_services.padatious_service:_match_level:50 - DEBUG - Padatious Matching confidence > 0.95

2024-05-11 23:17:15.239 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - intent matching took: 0.019217729568481445

2024-05-11 23:17:15.286 - skills - ovos_bus_client.client.client:on_default_session_update:161 - DEBUG - synced default_session

2024-05-11 23:17:15.350 - skills - ovos_bus_client.client.client:on_default_session_update:161 - DEBUG - synced default_session

2024-05-11 23:17:48.851 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-cancel: {}

2024-05-11 23:17:48.851 - skills - ovos_core.transformers:transform:63 - WARNING - ovos-utterance-corrections transform exception: list index out of range

2024-05-11 23:17:48.852 - skills - ovos_core.transformers:transform:60 - DEBUG - ovos-utterance-normalizer: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'de-de'}

2024-05-11 23:17:48.854 - skills - ovos_core.intent_services:get_pipeline:263 - DEBUG - Session pipeline: ['ocp_high', 'stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'ocp_medium', 'fallback_medium', 'ocp_fallback', 'fallback_low']

2024-05-11 23:17:48.855 - skills - padacioso:calc_intent:240 - INFO - No match

2024-05-11 23:17:48.856 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method OCPPipelineMatcher.match_high of <ovos_core.intent_services.ocp_service.OCPPipelineMatcher object at 0x75cbe0370190>>

2024-05-11 23:17:48.858 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x75cbe0597090>>

2024-05-11 23:17:48.874 - skills - ovos_core.intent_services:handle_utterance:376 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x75cbe0536910>>

2024-05-11 23:17:48.875 - skills - ovos_core.intent_services.padatious_service:_match_level:50 - DEBUG - Padatious Matching confidence > 0.95

2024-05-11 23:17:48.880 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - intent matching took: 0.02547287940979004

2024-05-11 23:17:48.933 - skills - ovos_bus_client.client.client:on_default_session_update:161 - DEBUG - synced default_session

skill-ovos-news.openvoiceos stopped: None

skill-ovos-youtube-music.openvoiceos stopped: None

skill-ovos-boot-finished.openvoiceos stopped: None

skill-openhab stopped: None

ovos.common_play stopped: None
```

**Comment by Dante1975X** [comment]
I now tried in English. And there it's working!

I find that strange. When I look to https://github.com/OpenVoiceOS/ovos-core/tree/dev/ovos_core/intent_services/locale/de-de there is a German stop.intent file and it looks fine....And why are the German versions of "pause" and "resume" working, even there are no German pause.intent and resume.intent files in that directory?
